### ISSUE TITLE
Compile for Movidius NCS

### ISSUE THREAD

**Issue by mdsimmo** [BeloborodovDS/MobilenetSSDFace#1]
Hello,

How can this be compiled for the Movidius NCS? Every time I try to compile a face detector, it fails.

The following code for the original ssd works (in models/ssd_voc):
`mvNCCompile -w MobileNetSSD_deploy.caffemodel -s 12 deploy.prototxt `

However, every other detector fails with a similar error message:
`mvNCCompile -s 12 -w best_bn_full.caffemodel ssd_face_deploy.prototxt`
results in:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0921 14:51:17.936494  7141 net.cpp:767] Check failed: target_blobs.size() == source_layer.blobs_size() (2 vs. 1) Incompatible number of blobs for layer conv0
*** Check failure stack trace: ***
Aborted (core dumped)
```

I've tried other combinations of prototxt and caffemodel, but all return a similar result. I dont know how to make it work?

Environment:

- ncsdk-1.12.00.01
- Ubunut 16.04

**Comment by BeloborodovDS** [comment]
@mdsimmo 
Hi!

This happens because you are trying to compile deploy-mode model with train-mode weights. Difference between those models is BatchNorm layers, which should be merged with scale layers for deploy for better performance. There is a script responsible for this: models/ssd_voc/merge_bn.py. 

There are two targets in Makefile of this project that you should use: `make deploy_full` or `make deploy_short`. These targets both convert corresponding .caffemodel to deploy mode and compile it to NCS, and place all files (.prototxt, .caffemodel, .graph) in models/deploy. (Seems like I forgot to mention it in README, will be fixed in next commit).

See target `deploy_full` for example:
`mkdir -p models/deploy &&	python3 models/ssd_voc/merge_bn.py models/ssd_face/ssd_face_train.prototxt models/ssd_face/best_bn_full.caffemodel models/ssd_face/ssd_face_deploy.prototxt models/deploy/ssd-face.caffemodel && cp -u -v models/ssd_face/ssd_face_deploy.prototxt models/deploy/ssd-face.prototxt && cd models/deploy && mvNCCompile ssd-face.prototxt -w ssd-face.caffemodel -s 12 -o ssd-face.graph && cd ../..`

**Comment by mdsimmo** [comment]
@BeloborodovDS  Ah. Okay. I try to run deploy_full but it fails because I believe it is looking for the LMBD database which I dont have. I'm currently downloading the dataset, but do you know if its possible to create the deploy version without it?

**Comment by BeloborodovDS** [comment]
@mdsimmo 

My bad. I forgot that Caffe requires setting data source in .prototxt (pretty weird, by the way). I will fix that later. Thanks for noticing.

You can:
a) replace the beginning of training .prototxt with the beginning of deploy .prototxt (input: "data" input_shape... instead of AnnotatedData layer)
b) Download converted models from my other repo: https://github.com/BeloborodovDS/NCS-face (in folder models/face)

**Comment by BeloborodovDS** [comment]
FIXED
1) Now targets for deploying/profiling/generating models do not depend on any LMDB databases.
2) Added deployment instructions to README

**Comment by mdsimmo** [comment]
Thanks @BeloborodovDS - that's really great :)
